ERROR_CODES = {
    16384: { "type": "Internal", "desc": "Internal error"},
    16385: { "type": "Memory", "desc": "Memory error"},
    16386: { "type": "Internal", "desc": "Nc retain data error (persistent data)"},
    16387: { "type": "Parameter", "desc": "Parameter for Monitoring the NC Setpoint Issuing is Invalid"},
    16388: { "type": "Internal", "desc": "External Error"},
    16400: { "type": "Parameter", "desc": "Channel identifier not allowed"},
    16401: { "type": "Parameter", "desc": "Group identifier not allowed"},
    16402: { "type": "Parameter", "desc": "Axis identifier not allowed"},
    16403: { "type": "Parameter", "desc": "Encoder identifier not allowed"},
    16404: { "type": "Parameter", "desc": "Controller identifier not allowed"},
    16405: { "type": "Parameter", "desc": "Drive identifier not allowed"},
    16406: { "type": "Parameter", "desc": "Table identifier not allowed"},
    16416: { "type": "Internal", "desc": "No process image"},
    16417: { "type": "Internal", "desc": "No process image"},
    16418: { "type": "Internal", "desc": "No process image"},
    16419: { "type": "Internal", "desc": "No process image"},
    16420: { "type": "Internal", "desc": "No process image"},
    16421: { "type": "Internal", "desc": "No process image"},
    16432: { "type": "Internal", "desc": "Coupling type not allowed"},
    16433: { "type": "Internal", "desc": "Axis type not allowed"},
    16434: { "type": "Parameter", "desc": "Unknown Channel Type"},
    16448: { "type": "Internal", "desc": "Axis is incompatible"},
    16464: { "type": "Internal", "desc": "Channel not ready for operation"},
    16465: { "type": "Internal", "desc": "Group not ready for operation"},
    16466: { "type": "Internal", "desc": "Axis not ready for operation"},
    16480: { "type": "Internal", "desc": "Channel exists"},
    16481: { "type": "Internal", "desc": "Group exists"},
    16482: { "type": "Internal", "desc": "Axis exists"},
    16483: { "type": "Internal", "desc": "Table exists"},
    16496: { "type": "Internal", "desc": "Axis index not allowed"},
    16497: { "type": "Internal", "desc": "Axis index not allowed"},
    16641: { "type": "Parameter", "desc": "Group index not allowed"},
    16642: { "type": "Address", "desc": "Null pointer"},
    16643: { "type": "Internal", "desc": "No process image"},
    16644: { "type": "Parameter", "desc": "M-function index not allowed"},
    16645: { "type": "Memory", "desc": "No memory"},
    16646: { "type": "Function", "desc": "Not ready"},
    16647: { "type": "Function", "desc": "Function/command not supported"},
    16648: { "type": "Parameter", "desc": "Invalid parameter while starting"},
    16649: { "type": "Function", "desc": "Channel function/command not executable"},
    16650: { "type": "Function", "desc": "ItpGoAhead not executable"},
    16656: { "type": "Parameter", "desc": "Error opening a file"},
    16657: { "type": "NC Programming", "desc": "Syntax error during loading"},
    16658: { "type": "NC Programming", "desc": "Syntax error during interpretation"},
    16659: { "type": "NC Programming", "desc": "Missing subroutine"},
    16660: { "type": "Memory", "desc": "Loading buffer of interpreter is too small"},
    16661: { "type": "Internal", "desc": "“Symbolic”"},
    16662: { "type": "Internal", "desc": "“Symbolic”"},
    16663: { "type": "NC Programming", "desc": "Subroutine incomplete"},
    16664: { "type": "NC Programming", "desc": "Error while loading the NC program"},
    16665: { "type": "NC Programming", "desc": "Error while loading the NC program"},
    16672: { "type": "NC Programming", "desc": "Divide by zero"},
    16673: { "type": "NC Programming", "desc": "Invalid circle parameterization"},
    16674: { "type": "NC Programming", "desc": "Invalid FPU-Operation"},
    16688: { "type": "NC Programming", "desc": "Stack overflow: subroutines"},
    16689: { "type": "NC Programming", "desc": "Stack underflow: subroutines"},
    16690: { "type": "NC Programming", "desc": "Stack overflow: arithmetic unit"},
    16691: { "type": "NC Programming", "desc": "Stack underflow: arithmetic unit"},
    16704: { "type": "Parameter", "desc": "Register index not allowed"},
    16705: { "type": "NC Programming", "desc": "Unacceptable G-function index"},
    16706: { "type": "NC Programming", "desc": "Unacceptable M-function index"},
    16707: { "type": "NC Programming", "desc": "Unacceptable extended address"},
    16708: { "type": "NC Programming", "desc": "Unacceptable index to the internal H-function"},
    16709: { "type": "Parameter", "desc": "Machine data value unacceptable"},
    16720: { "type": "Parameter", "desc": "Cannot change tool params here"},
    16721: { "type": "Parameter", "desc": "Cannot calculate tool compensation"},
    16722: { "type": "NC Programming", "desc": "Tool compensation: The plane for the tool compensation cannot be changed here"},
    16723: { "type": "NC Programming", "desc": "Tool compensation: The D-Word is missing or invalid by turning on the tool compensation"},
    16724: { "type": "NC Programming", "desc": "Tool compensation: The specified tool radius is invalid because the value is less or equal zero"},
    16725: { "type": "NC Programming", "desc": "Tool compensation: The tool radius cannot be changed here"},
    16726: { "type": "Internal", "desc": "Tool compensation: Collision Detection Table is full"},
    16727: { "type": "Internal", "desc": "Tool compensation: Internal error while turning on the contour collision detection"},
    16728: { "type": "Internal", "desc": "Tool compensation: Internal error within the contour collision detection: update reversed geo failed"},
    16729: { "type": "NC Programming", "desc": "Tool compensation: Unexpected combination of geometry types by active contour collision detection"},
    16730: { "type": "NC Programming", "desc": "Tool compensation: Programmed inner circle is smaller than the cutter radius"},
    16731: { "type": "NC Programming", "desc": "Tool compensation: Bottle neck detection recognized contour violation"},
    16732: { "type": "Memory", "desc": "Table for corrected entries is full"},
    16733: { "type": "Memory", "desc": "Input table for tangential following is full"},
    16734: { "type": "Memory", "desc": "Executing table for tangential following is full"},
    16735: { "type": "Internal", "desc": "Geometric entry for tangential following cannot be calculated"},
    16736: { "type": "Internal", "desc": "reserved"},
    16737: { "type": "Internal", "desc": "reserved"},
    16738: { "type": "Parameter", "desc": "The actual active interpolation rules (g-code), zero-shifts, or rotation cannot be detected"},
    16752: { "type": "NC Programming", "desc": "Error while loading: Invalid parameter"},
    16753: { "type": "Internal", "desc": "Invalid contour start position"},
    16754: { "type": "Internal", "desc": "Retrace: Invalid internal entry index"},
    16755: { "type": "NC Programming", "desc": "Invalid G Code"},
    16756: { "type": "NC Programming", "desc": "Error while Opening the G Code File"},
    16896: { "type": "Parameter", "desc": "Group ID not allowed"},
    16897: { "type": "Parameter", "desc": "Group type not allowed"},
    16898: { "type": "Initialization", "desc": "Master axis index not allowed"},
    16899: { "type": "Initialization", "desc": "Slave axis index not allowed"},
    16900: { "type": "Initialization", "desc": "Internal Error"},
    16901: { "type": "Parameter", "desc": "Invalid cycle time for statement execution task (SAF)"},
    16902: { "type": "Initialization", "desc": "GROUPERR_RANGE_MAXELEMENTSINAXIS "},
    16903: { "type": "Parameter", "desc": "Invalid cycle time for the statement preparation task (SVB)"},
    16904: { "type": "Parameter", "desc": "Single step mode not allowed"},
    16905: { "type": "Parameter", "desc": "Group deactivation not allowed"},
    16906: { "type": "Initialization", "desc": "Statement execution state (SAF state) not allowed (INTERNAL ERROR)"},
    16907: { "type": "Address", "desc": "Channel address"},
    16908: { "type": "Address", "desc": "Axis address (master axis)"},
    16909: { "type": "Address", "desc": "Master axis address"},
    16910: { "type": "Address", "desc": "Slave axis address"},
    16911: { "type": "Address", "desc": "Slave set value generator address"},
    16912: { "type": "Address", "desc": "Encoder address"},
    16913: { "type": "Address", "desc": "Controller address"},
    16914: { "type": "Address", "desc": "Drive address"},
    16915: { "type": "Address", "desc": "Address Master Setpoint Generator"},
    16916: { "type": "Address", "desc": "Axis interface NC to PLC address"},
    16917: { "type": "Address", "desc": "Slave axis address"},
    16918: { "type": "Address", "desc": "Table address unknown"},
    16919: { "type": "Address", "desc": "NcControl address"},
    16920: { "type": "Initialization", "desc": "Axis is blocked for commands while persistent NC data are queued"},
    16921: { "type": "Function", "desc": "The scaling mode MASTER-AUTOOFFSET is invalid because no reference table was found"},
    16922: { "type": "Parameter", "desc": "The master axis start position does not permit synchronization"},
    16923: { "type": "Parameter", "desc": "Slave coupling factor (gearing factor) of 0.0 is not allowed"},
    16924: { "type": "Function", "desc": "Insertion of master axis into group not allowed"},
    16925: { "type": "Function", "desc": "Deletion of master axis from group not allowed (INTERNAL ERROR)"},
    16926: { "type": "Function", "desc": "Function/feature is not supported from the setpoint generator"},
    16927: { "type": "Initialization", "desc": "Group initialization"},
    16928: { "type": "Monitoring", "desc": "Group not ready / group not ready for new task"},
    16929: { "type": "Monitoring", "desc": "Requested set velocity is not allowed"},
    16930: { "type": "Monitoring", "desc": "Requested target position is not allowed (master axis)"},
    16931: { "type": "Monitoring", "desc": "No enable for controller and/or feed (Master axis)"},
    16932: { "type": "Monitoring", "desc": "Movement smaller than one encoder increment"},
    16933: { "type": "Monitoring", "desc": "Drive not ready during axis start"},
    16934: { "type": "Monitoring", "desc": "Invalid parameters of the emergency stop."},
    16935: { "type": "Function", "desc": "The setpoint generator is inactive such that no instructions are accepted"},
    16936: { "type": "Monitoring", "desc": "Requested traverse distance is not allowed"},
    16937: { "type": "Monitoring", "desc": "Requested target position is not allowed (slave axis)"},
    16938: { "type": "Monitoring", "desc": "No enable for controller and/or feed (slave axis)"},
    16939: { "type": "Parameter", "desc": "The activation position (position threshold) is out of range of the actual positioning"},
    16940: { "type": "Parameter", "desc": "The start or activation data of the external setpoint generation are not valid"},
    16941: { "type": "Parameter", "desc": "Velocity is not constant"},
    16942: { "type": "Parameter", "desc": "Jerk less than or equal to 0.0 is not allowed"},
    16943: { "type": "Parameter", "desc": "Acceleration less than or equal to 0.0 is not allowed"},
    16944: { "type": "Parameter", "desc": "Absolute deceleration value less than or equal to 0.0 is not allowed"},
    16945: { "type": "Parameter", "desc": "Set velocity less than or equal to 0.0 is not allowed"},
    16946: { "type": "Monitoring", "desc": "Loss of precision when trying a positioning"},
    16947: { "type": "Parameter", "desc": "Cycle time less than or equal to 0.0 is not allowed"},
    16948: { "type": "Internal", "desc": "PTP data type <intasdouble> range exceeded"},
    16949: { "type": "Function", "desc": "PTP LHL velocity profile cannot be generated"},
    16950: { "type": "Function", "desc": "PTP HML velocity profile cannot be generated"},
    16951: { "type": "Address", "desc": "Start data address is invalid"},
    16952: { "type": "Parameter", "desc": "Velocity override (start override) is not allowed"},
    16953: { "type": "Parameter", "desc": "Start type not allowed"},
    16954: { "type": "Monitoring", "desc": "Velocity overflow (overshoot in the velocity)"},
    16955: { "type": "Parameter", "desc": "Start parameter for the axis structure is invalid"},
    16956: { "type": "Parameter", "desc": "Override generator initialization parameter invalid"},
    16957: { "type": "Monitoring", "desc": "Slave axis has not set value generator"},
    16958: { "type": "Function", "desc": "Table is empty"},
    16959: { "type": "Function", "desc": "Table is full"},
    16960: { "type": "Memory", "desc": "No memory available"},
    16961: { "type": "Function", "desc": "Table already contains an entry"},
    16962: { "type": "Function", "desc": "Stop is already active"},
    16963: { "type": "Function", "desc": "Compensation has not been carried out over the full compensation section"},
    16964: { "type": "Parameter", "desc": "Internal parameters for the compensation are invalid"},
    16965: { "type": "Function", "desc": "Compensation active"},
    16966: { "type": "Function", "desc": "Compensation not active"},
    16967: { "type": "Function", "desc": "Compensation type invalid"},
    16968: { "type": "Function", "desc": "Axis address for compensation invalid"},
    16969: { "type": "Address", "desc": "Invalid slave address"},
    16970: { "type": "Function", "desc": "Coupling velocity invalid"},
    16971: { "type": "Function", "desc": "Coupling velocities not constant"},
    16972: { "type": "Parameter", "desc": "Cycle time less than or equal to 0.0 is not allowed"},
    16973: { "type": "Function", "desc": "Decoupling task not allowed"},
    16974: { "type": "Function", "desc": "Function not allowed"},
    16975: { "type": "Parameter", "desc": "No valid table weighting has been set"},
    16976: { "type": "Function", "desc": "Axis type, actual position type or end position type is not allowed"},
    16977: { "type": "Function", "desc": "Function not presently supported"},
    16978: { "type": "Monitoring", "desc": "State of state machine invalid (INTERNAL ERROR)"},
    16979: { "type": "Monitoring", "desc": "Reference cam became free too soon"},
    16980: { "type": "Monitoring", "desc": "Clearance monitoring between activation of the hardware latch and appearance of the sync pulse"},
    16981: { "type": "Memory", "desc": "No memory available"},
    16982: { "type": "Monitoring", "desc": "The table slave axis has no active table"},
    16983: { "type": "Function", "desc": "Function not allowed"},
    16984: { "type": "Function", "desc": "Stopping compensation not allowed"},
    16985: { "type": "Function", "desc": "Slave table is being used"},
    16986: { "type": "Function", "desc": "Master or slave axis is processing a job (e.g. positioning command) while coupling is requested"},
    16987: { "type": "Parameter", "desc": "Slave (start) parameter is incorrect"},
    16988: { "type": "Parameter", "desc": "Slave type is incorrect"},
    16989: { "type": "Function", "desc": "Axis stop is already active"},
    16990: { "type": "Function", "desc": "Maximum number of tables per slavegenerator reached"},
    16991: { "type": "Function", "desc": "The scaling mode is invalid"},
    16992: { "type": "Monitoring", "desc": "Controller enable"},
    16993: { "type": "Function", "desc": "Table not found"},
    16994: { "type": "Function", "desc": "Incorrect table type"},
    16995: { "type": "Function", "desc": "Single step mode"},
    16996: { "type": "Function", "desc": "Group task unknown (asynchronous table entry)"},
    16997: { "type": "Function", "desc": "Group function unknown (synchronous function)"},
    16998: { "type": "Function", "desc": "Group task for slave not allowed"},
    16999: { "type": "Function", "desc": "Group function for slave not allowed"},
    17000: { "type": "Function", "desc": "NCI Setpoint Generator is Inactive"},
    17001: { "type": "Parameter", "desc": "Startposition=Setpoint Position"},
    17002: { "type": "Parameter", "desc": "Parameters of the delay-generator are invalid"},
    17003: { "type": "Parameter", "desc": "External parameters of the superimposed instruction are invalid"},
    17004: { "type": "Parameter", "desc": "Invalid override type."},
    17005: { "type": "Function", "desc": "Activation position under/overrun"},
    17006: { "type": "Function", "desc": "Activation impossible: Master is standing"},
    17007: { "type": "Function", "desc": "Activation mode not possible"},
    17008: { "type": "Parameter", "desc": "Start parameter for the compensation is invalid"},
    17009: { "type": "Parameter", "desc": "Start parameter for the compensation is invalid"},
    17010: { "type": "Parameter", "desc": "Start parameter for the compensation is invalid"},
    17011: { "type": "Monitoring", "desc": "Target position under/overrun (INTERNAL ERROR)"},
    17012: { "type": "Monitoring", "desc": "Target position will be under/overrun (INTERNAL ERROR)"},
    17013: { "type": "Parameter", "desc": "Group Parameter is Invalid"},
    17014: { "type": "Monitoring", "desc": "Joint Error at Start of Setpoint Generation"},
    17015: { "type": "Monitoring", "desc": "Dynamic parameters not permitted"},
    17017: { "type": "Monitoring", "desc": "The New Target Position is Invalid or Cannot be Reached"},
    17018: { "type": "Monitoring", "desc": "New Velocity for Moving or the Final Target Velocity is Invalid"},
    17019: { "type": "Monitoring", "desc": "The Final Velocity or the New Target Position is Invalid"},
    17020: { "type": "Monitoring", "desc": "The New Moving Velocity is Invalid"},
    17021: { "type": "Monitoring", "desc": "Internal Starting Mode is Invalid"},
    17022: { "type": "Monitoring", "desc": "A requested motion command could not be realized (BISECTION)"},
    17023: { "type": "Monitoring", "desc": "The new target position either has been overrun or will be overrun"},
    17024: { "type": "Monitoring", "desc": "Group not ready / group not ready for new task"},
    17025: { "type": "Parameter", "desc": "The parameters of the oriented stop (O-Stop) are not admitted."},
    17026: { "type": "Monitoring", "desc": "The modulo target position of the modulo-start is invalid"},
    17027: { "type": "Parameter", "desc": "The online change activation mode is invalid."},
    17028: { "type": "Parameter", "desc": "The parameterized jerk rate is not permitted."},
    17029: { "type": "Parameter", "desc": "The parameterized acceleration or deceleration is not permitted."},
    17030: { "type": "Parameter", "desc": "The parameterized velocity is not permitted."},
    17031: { "type": "Monitoring", "desc": "A activation cannot be executed due to a pending activation"},
    17032: { "type": "Monitoring", "desc": "Illegal combination of different cycle times within an axis group"},
    17033: { "type": "Monitoring", "desc": "Illegal motion reversal"},
    17034: { "type": "Monitoring", "desc": "Illegal moment for an axis command because there is an old axis command with activation position still active"},
    17035: { "type": "Monitoring", "desc": "Error in the stop-calculation routine"},
    17036: { "type": "Monitoring", "desc": "A command with activation position cannot fully be performed because the remaining path is too short"},
    17037: { "type": "Monitoring", "desc": "Illegal decouple type when decoupling a slave axis"},
    17038: { "type": "Monitoring", "desc": "Illegal target velocity when decoupling a slave axis"},
    17039: { "type": "Monitoring", "desc": "The command new dynamic parameter cannot be performed since this would require a new target velocity"},
    17040: { "type": "Monitoring", "desc": "A command with activation position cannot be performed because the axis is already in the brake phase"},
    17041: { "type": "Monitoring", "desc": "Decouple routine of slave axis doesn't return a valid solution"},
    17042: { "type": "Monitoring", "desc": "Command not be executed because the command buffer is full filled"},
    17043: { "type": "Internal", "desc": "Command is rejected due to an internal error in the Look Ahead"},
    17044: { "type": "Monitoring", "desc": "Command is rejected because the segment target velocity is not realized"},
    17045: { "type": "Monitoring", "desc": "Successive commands have the same final position"},
    17046: { "type": "Monitoring", "desc": "Logical positioning direction is inconsistent with the direction of the buffer command"},
    17047: { "type": "Monitoring", "desc": "Command is rejected because the remaining positioning length is to small"},
    17050: { "type": "Function", "desc": "Restart has Failed"},
    17051: { "type": "Monitoring", "desc": "collect error for invalid start parameters"},
    17052: { "type": "Monitoring", "desc": "Reference cam is not found"},
    17053: { "type": "Monitoring", "desc": "Reference cam became not free"},
    17054: { "type": "Monitoring", "desc": "IO sync pulse was not found (only when using hardware latch)"},
    17055: { "type": "Function", "desc": "The Used Buffer Mode is Unknown or not Supported in this Context"},
    17056: { "type": "Internal", "desc": "Group/axis consequential error"},
    17057: { "type": "Parameter", "desc": "Velocity reduction factor for C0/C1 transition is not allowed"},
    17058: { "type": "Parameter", "desc": "Critical angle at segment transition not allowed"},
    17059: { "type": "Parameter", "desc": "Radius of the tolerance sphere"},
    17060: { "type": "Parameter", "desc": "Not implemented."},
    17061: { "type": "Parameter", "desc": "Start type"},
    17062: { "type": "Parameter", "desc": "Not implemented."},
    17063: { "type": "Parameter", "desc": "Blending"},
    17064: { "type": "Parameter", "desc": "Not implemented."},
    17065: { "type": "Parameter", "desc": "Curve velocity reduction method not allowed"},
    17066: { "type": "Parameter", "desc": "Minimum velocity not allowed"},
    17067: { "type": "Parameter", "desc": "Power function input not allowed"},
    17068: { "type": "Parameter", "desc": "Dynamic change parameter not allowed"},
    17069: { "type": "Memory", "desc": "Memory allocation error"},
    17070: { "type": "Function", "desc": "The calculated end position differs from the end position in the nc instruction "},
    17071: { "type": "Parameter", "desc": "Calculate remaining chord length"},
    17072: { "type": "Function", "desc": "Set value generator SVB active"},
    17073: { "type": "Parameter", "desc": "SVB parameter not allowed"},
    17074: { "type": "Parameter", "desc": "Velocity reduction factor not allowed"},
    17075: { "type": "Parameter", "desc": "Helix is a circle"},
    17076: { "type": "Parameter", "desc": "Helix is a straight line"},
    17077: { "type": "Parameter", "desc": "Guider parameter not allowed"},
    17078: { "type": "Address", "desc": "Invalid segment address"},
    17079: { "type": "Parameter", "desc": "Unparameterized generator"},
    17080: { "type": "Address", "desc": "Unparameterized table"},
    17082: { "type": "Internal", "desc": "The calculation of the arc length of the smoothed path failed (internal error)."},
    17083: { "type": "Parameter", "desc": "The radius of the tolerance ball is too small (smaller than 0.1 mm)"},
    17084: { "type": "Internal", "desc": "Error while calculating DXD-Software-Limit switches (internal error)"},
    17085: { "type": "Function", "desc": "NC-Block violates software limit switches of the group"},
    17086: { "type": "Parameter", "desc": "“Internal error in the evaluation of a possible software limit switch violation for the segment with the block-number xx.” At least one path axis with active position limit monitoring has violated the limit switches."},
    17087: { "type": "Parameter", "desc": "Invalid reference speed type"},
    17088: { "type": "Internal", "desc": "Interpolating group contains axes of an incorrect axis type"},
    17089: { "type": "Internal", "desc": "Scalar product cannot be calculated"},
    17090: { "type": "Internal", "desc": "Inverse cosine cannot be calculated"},
    17091: { "type": "Parameter", "desc": "Invalid table entry type"},
    17092: { "type": "Parameter", "desc": "Invalid DIN66025 information type"},
    17093: { "type": "Parameter", "desc": "Invalid dimension"},
    17094: { "type": "Parameter", "desc": "Geometrical object is not a straight line"},
    17095: { "type": "Parameter", "desc": "Geometrical object is not a circle"},
    17096: { "type": "Parameter", "desc": "Geometrical object is not a helix"},
    17097: { "type": "Parameter", "desc": "Set velocity less than or equal to 0.0 is invalid"},
    17098: { "type": "Address", "desc": "Address for look-ahead invalid"},
    17099: { "type": "Function", "desc": "Set value generator SAF active"},
    17100: { "type": "Function", "desc": "CNC set value generation not active"},
    17101: { "type": "Function", "desc": "CNC set value generation in the stop phase"},
    17102: { "type": "Parameter", "desc": "Override not allowed"},
    17103: { "type": "Address", "desc": "Invalid table address"},
    17104: { "type": "Parameter", "desc": "Invalid table entry type"},
    17105: { "type": "Memory", "desc": "Memory allocation failed"},
    17106: { "type": "Memory", "desc": "Memory allocation failed"},
    17107: { "type": "Parameter", "desc": "Invalid parameter"},
    17108: { "type": "Function", "desc": "Delete Distance To Go failed"},
    17109: { "type": "Internal", "desc": "The setpoint generator of the flying saw generates incompatible values (internal error)"},
    17110: { "type": "Function", "desc": "Axis will be stopped since otherwise it will overrun its target position (old PTP setpoint generator)"},
    17111: { "type": "Function", "desc": "Internal error in the transformation from slave to master."},
    17112: { "type": "Function", "desc": "Wrong direction in the transformation of slave to master"},
    17114: { "type": "Parameter", "desc": "Parameter of Motion Function (MF) table incorrect"},
    17115: { "type": "Parameter", "desc": "Parameter of Motion Function (MF) table incorrect"},
    17116: { "type": "Monitoring", "desc": "Internal error by using Motion Function (MF)"},
    17117: { "type": "Function", "desc": "Axis coupling with synchronization generator declined because of incorrect axis dynamic values"},
    17118: { "type": "Function", "desc": "Coupling conditions of synchronization generator incorrect"},
    17119: { "type": "Monitoring", "desc": "Moving profile of synchronization generator declines dynamic limit of slave axis or required characteristic of profile"},
    17120: { "type": "Parameter", "desc": "Invalid parameter"},
    17121: { "type": "Parameter", "desc": "Invalid parameter"},
    17122: { "type": "Function", "desc": "External generator is active"},
    17123: { "type": "Function", "desc": "External generator is not active"},
    17124: { "type": "Function", "desc": "NC-Block with auxiliary axis violates software limit switches of the group"},
    17125: { "type": "Function", "desc": "NC-Block type Bezier spline curve contains a cusp (singularity)"},
    17127: { "type": "Parameter", "desc": "Value for dead time compensation not allowed"},
    17128: { "type": "Parameter", "desc": "GROUPERR_RANGE_NOMOTIONWINDOW"},
    17129: { "type": "Parameter", "desc": "GROUPERR_RANGE_NOMOTIONFILTERTIME"},
    17130: { "type": "Parameter", "desc": "GROUPERR_RANGE_TIMEUNITFIFO"},
    17131: { "type": "Parameter", "desc": "GROUPERR_RANGE_OVERRIDETYPE"},
    17132: { "type": "Parameter", "desc": "GROUPERR_RANGE_OVERRIDECHANGETIME"},
    17133: { "type": "Parameter", "desc": "GROUPERR_FIFO_INVALIDDIMENSION"},
    17134: { "type": "Address", "desc": "GROUPERR_ADDR_FIFOTABLE"},
    17135: { "type": "Monitoring", "desc": "Axis is locked for motion commands because a stop command is still active"},
    17136: { "type": "Parameter", "desc": "Invalid number of auxiliary axes"},
    17137: { "type": "Parameter", "desc": "Invalid reduction parameter for auxiliary axes"},
    17138: { "type": "Parameter", "desc": "Invalid dynamic parameter for auxiliary axes"},
    17139: { "type": "Parameter", "desc": "Invalid coupling parameter for auxiliary axes"},
    17140: { "type": "Parameter", "desc": "Invalid auxiliary axis entry"},
    17142: { "type": "Parameter", "desc": "Invalid parameter"},
    17144: { "type": "Parameter", "desc": "Block search - segment not found"},
    17145: { "type": "Parameter", "desc": "Blocksearch – invalid remaining segment length"},
    17147: { "type": "Internal", "desc": "Internal Error in the Context of Coupled Axes (Slave Axes)"},
    17148: { "type": "Parameter", "desc": "Parameter for the Maximum Number of Jobs (Entries) to be Transferred is Invalid"},
    17151: { "type": "Monitoring", "desc": "Customer Specific Error"},
    17152: { "type": "Parameter", "desc": "Axis ID not allowed"},
    17153: { "type": "Parameter", "desc": "Axis type not allowed"},
    17158: { "type": "Parameter", "desc": "Slow manual velocity not allowed"},
    17159: { "type": "Parameter", "desc": "Fast manual velocity not allowed"},
    17160: { "type": "Parameter", "desc": "High speed not allowed"},
    17161: { "type": "Parameter", "desc": "Acceleration not allowed"},
    17162: { "type": "Parameter", "desc": "Deceleration not allowed"},
    17163: { "type": "Parameter", "desc": "Jerk not allowed"},
    17164: { "type": "Parameter", "desc": "Delay time between position and velocity is not allowed (dead time compensation)"},
    17165: { "type": "Parameter", "desc": "Override type not allowed"},
    17166: { "type": "Parameter", "desc": "NCI: Velo-Jump-Factor not allowed"},
    17167: { "type": "Parameter", "desc": "NCI: Size of tolerance sphere for auxiliary axis invalid"},
    17168: { "type": "Parameter", "desc": "NCI: Value for maximum deviation for auxiliary axis invalid"},
    17170: { "type": "Parameter", "desc": "Referencing velocity in direction of cam not allowed"},
    17171: { "type": "Parameter", "desc": "Referencing velocity in sync direction not allowed"},
    17172: { "type": "Parameter", "desc": "Pulse width in positive direction not allowed"},
    17173: { "type": "Parameter", "desc": "Pulse width in negative direction not allowed"},
    17174: { "type": "Parameter", "desc": "Pulse time in positive direction not allowed"},
    17175: { "type": "Parameter", "desc": "Pulse time in negative direction not allowed"},
    17176: { "type": "Parameter", "desc": "Creep distance in positive direction not allowed"},
    17177: { "type": "Parameter", "desc": "Creep distance in negative direction not allowed"},
    17178: { "type": "Parameter", "desc": "Braking distance in positive direction not allowed"},
    17179: { "type": "Parameter", "desc": "Braking distance in negative direction not allowed"},
    17180: { "type": "Parameter", "desc": "Braking time in positive direction not allowed"},
    17181: { "type": "Parameter", "desc": "Braking time in negative direction not allowed"},
    17182: { "type": "Parameter", "desc": "Switching time from high to low speed not allowed"},
    17183: { "type": "Parameter", "desc": "Creep distance for stop not allowed"},
    17184: { "type": "Parameter", "desc": "Motion monitoring time not allowed"},
    17185: { "type": "Parameter", "desc": "Position window monitoring not allowed"},
    17186: { "type": "Parameter", "desc": "Target window monitoring not allowed"},
    17187: { "type": "Parameter", "desc": "Loop not allowed"},
    17188: { "type": "Parameter", "desc": "Motion monitoring time not allowed"},
    17189: { "type": "Parameter", "desc": "Target window range not allowed"},
    17190: { "type": "Parameter", "desc": "Position window range not allowed"},
    17191: { "type": "Parameter", "desc": "Position window monitoring time not allowed"},
    17192: { "type": "Parameter", "desc": "Loop movement not allowed"},
    17193: { "type": "Parameter", "desc": "Axis cycle time not allowed"},
    17194: { "type": "Parameter", "desc": "Stepper motor operating mode not allowed"},
    17195: { "type": "Parameter", "desc": "Displacement per stepper motor step not allowed"},
    17196: { "type": "Parameter", "desc": "Minimum speed for stepper motor set value profile not allowed"},
    17197: { "type": "Parameter", "desc": "Stepper motor steps per speed level not allowed"},
    17198: { "type": "Parameter", "desc": "DWORD for the interpretation of the axis units not allowed"},
    17199: { "type": "Parameter", "desc": "Maximum velocity not allowed"},
    17200: { "type": "Parameter", "desc": "Motion monitoring window not allowed"},
    17201: { "type": "Parameter", "desc": "PEH time monitoring not allowed"},
    17202: { "type": "Parameter", "desc": "PEH monitoring time not allowed"},
    17203: { "type": "Parameter", "desc": "Parameter 'Brake Release Delay' is invalid"},
    17204: { "type": "Parameter", "desc": "Parameter 'NC Data Persistence' is invalid"},
    17205: { "type": "Parameter", "desc": "Parameter for Error Reaction Mode is invalid"},
    17206: { "type": "Parameter", "desc": "Parameter for the Error Reaction Delay is invalid"},
    17207: { "type": "Parameter", "desc": "Parameter 'Use actual values in deactivated state' is invalid"},
    17208: { "type": "Parameter", "desc": "Parameter 'Allow Motion Commands for Slave Axes' is invalid"},
    17209: { "type": "Parameter", "desc": "Parameter 'Allow Motion Commands for axis in external setpoint generation' is invalid"},
    17210: { "type": "Parameter", "desc": "Parameter 'Fading Acceleration' is invalid"},
    17211: { "type": "Parameter", "desc": "'Fast Axis Stop' signal type not allowed"},
    17216: { "type": "Initialization", "desc": "Axis initialization: Axis has not been initialized"},
    17217: { "type": "Address", "desc": "Group address: Axis does not have a group, or the group address has not been initialized (group contains the setpoint generation)"},
    17218: { "type": "Address", "desc": "Encoder address: The axis does not have an encoder, or the encoder address has not been initialized"},
    17219: { "type": "Address", "desc": "Controller address:An axis does not have a controller, or the controller address has not been initialized"},
    17220: { "type": "Address", "desc": "Drive address: The axis does not have a drive, or the drive address has not been initialized"},
    17221: { "type": "Address", "desc": "Axis interface PLC to NC address: Axis does not have an axis interface from the PLC to the NC, or the axis interface address has not been initialized"},
    17222: { "type": "Address", "desc": "Axis interface NC to PLC address: Axis does not have an axis interface from the NC to the PLC, or the axis interface address has not been initialized"},
    17223: { "type": "Address", "desc": "Size of axis interface NC to PLC not allowed"},
    17224: { "type": "Address", "desc": " Size of axis interface PLC to NC not allowed"},
    17238: { "type": "Monitoring", "desc": "Controller enable: Controller enable for the axis is not present"},
    17239: { "type": "Monitoring", "desc": "Feed enable negative: There is no feed enable for negative motion direction "},
    17240: { "type": "Monitoring", "desc": "Feed enable plus: Feed enable for movement in the positive direction is not present"},
    17241: { "type": "Monitoring", "desc": "Set velocity not allowed"},
    17242: { "type": "Monitoring", "desc": "Movement smaller than one encoder increment"},
    17243: { "type": "Monitoring", "desc": "Set acceleration monitoring: The set acceleration has exceeded the maximum permitted acceleration or deceleration parameters of the axis"},
    17244: { "type": "Monitoring", "desc": "PEH time monitoring: The PEH time monitoring has detected that, after the PEH monitoring time that follows a positioning has elapsed, the target position window has not been reached"},
    17245: { "type": "Monitoring", "desc": "Motion Monitoring: . To avoid an error, the axis must change by more than the parameterized motion monitoring window in at least one NC cycle during the monitoring time"},
    17246: { "type": "Monitoring", "desc": "Looping distance less than breaking distance"},
    17247: { "type": "Monitoring", "desc": "Starting velocity not allowed"},
    17248: { "type": "Monitoring", "desc": "Final velocity not allowed"},
    17249: { "type": "Monitoring", "desc": "Time range exceeded (future)"},
    17250: { "type": "Monitoring", "desc": "Time range exceeded (past)"},
    17251: { "type": "Monitoring", "desc": "Position cannot be determined"},
    17252: { "type": "Monitoring", "desc": "Position indeterminable (conflicting direction of travel)"},
    17264: { "type": "Monitoring", "desc": "No slave coupling possible (velocity violation)"},
    17265: { "type": "Monitoring", "desc": "No slave coupling possible (acceleration violation)"},
    17312: { "type": "Internal", "desc": "Axis consequential error"},
    17408: { "type": "Parameter", "desc": "Encoder ID not allowed"},
    17409: { "type": "Parameter", "desc": "Encoder type not allowed"},
    17410: { "type": "Parameter", "desc": "Encoder mode: The value for the encoder (operating) mode is not allowed"},
    17411: { "type": "Parameter", "desc": "Encoder counting direction inverted"},
    17412: { "type": "Initialization", "desc": "Referencing status: The flag for the referencing status is not allowed"},
    17413: { "type": "Parameter", "desc": "Encoder increments for each physical encoder rotation: The value for the number of encoder increments for each physical rotation of the encoder is not allowed"},
    17414: { "type": "Parameter", "desc": "Scaling factor The value for the scaling factor is not allowed. This scaling factor provides the weighting for the conversion of an encoder increment (INC) to a physical unit such as millimeters or degrees."},
    17415: { "type": "Parameter", "desc": "Position offset (zero point offset): The value for the position offset of the encoder is not allowed"},
    17416: { "type": "Parameter", "desc": "Modulo factor The value for the encoder's modulo factor is not allowed."},
    17417: { "type": "Parameter", "desc": "Position filter time: The value for the actual position filter time is not allowed (P-T1 filter)"},
    17418: { "type": "Parameter", "desc": "Velocity filter time The value for the actual velocity filter time is not allowed (P-T1 filter)."},
    17419: { "type": "Parameter", "desc": "Acceleration filter time: The value for the actual acceleration filter time is not allowed (P-T1 filter)"},
    17420: { "type": "Initialization", "desc": "Cycle time not allowed (INTERNAL ERROR) The value of the SAF cycle time for the calculation of actual values is not allowed (e.g. is less than or equal to zero)."},
    17421: { "type": "Initialization", "desc": "“Configuration of the selected units is invalid”"},
    17422: { "type": "Parameter", "desc": "Actual position correction / measurement system error correction: The value for the activation of the actual position correction (measuring system error correction) is not allowed"},
    17423: { "type": "Parameter", "desc": "Filter time actual position correction: The value for the actual position correction filter time is not allowed (P-T1 filter)"},
    17424: { "type": "Parameter", "desc": "Search direction for referencing cam inverted The value of the search direction of the referencing cam in a referencing procedure is not allowed. Value 0: Positive direction Value 1: Negative direction"},
    17425: { "type": "Parameter", "desc": "Search direction for sync pulse (zero pulse) inverted: The value of the search direction of the sync pulse (zero pulse) in a referencing procedure is not allowed"},
    17426: { "type": "Parameter", "desc": "Reference position: The value of the reference position in a referencing procedure is not allowed"},
    17427: { "type": "Parameter", "desc": "Clearance monitoring between activation of the hardware latch and appearance of the sync pulse (NOT IMPLEMENTED)"},
    17428: { "type": "Parameter", "desc": "Minimum clearance between activation of the hardware latch and appearance of the sync pulse (NOT IMPLEMENTED) The value for the minimum clearance in increments between activation of the hardware latch and occurrence of the sync/zero pulse (latch valid) during a referencing procedure is not allowed."},
    17429: { "type": "Parameter", "desc": "External sync pulse (NOT IMPLEMENTED)"},
    17430: { "type": "Parameter", "desc": "Scaling of the noise rate is not allowed"},
    17431: { "type": "Parameter", "desc": "Tolerance window for modulo-start: The value for the tolerance window for the modulo-axis-start is invalid"},
    17432: { "type": "Parameter", "desc": "Encoder reference mode: The value for the encoder reference mode is not allowed"},
    17433: { "type": "Parameter", "desc": "Encoder evaluation direction: The value for the encoder evaluation direction (log. counter direction) is not allowed"},
    17434: { "type": "Parameter", "desc": "Encoder reference system: The value for the encoder reference system is invalid"},
    17435: { "type": "Parameter", "desc": "Encoder position initialization mode: When starting the TC system the value for the encoder position initialization mode is invalid"},
    17436: { "type": "Parameter", "desc": "Encoder sign interpretation (UNSIGNED- / SIGNED- data type): The value for the encoder sign interpretation (data type) for the encoder the actual increment calculation"},
    17437: { "type": "Parameter", "desc": "Homing Sensor Source: The value for the encoder homing sensor source is not allowed"},
    17440: { "type": "Parameter", "desc": "Software end location monitoring minimum not allowed"},
    17441: { "type": "Parameter", "desc": "Software end location monitoring maximum not allowed"},
    17442: { "type": "Function", "desc": "Actual value setting is outside the value range"},
    17443: { "type": "Parameter", "desc": "Software end location minimum not allowed"},
    17444: { "type": "Parameter", "desc": "Software end location maximum not allowed"},
    17445: { "type": "Parameter", "desc": "Filter mask for the raw data of the encoder is invalid"},
    17446: { "type": "Parameter", "desc": "„Reference mask for the raw data of the encoder is invalid“ The value for the reference mask (increments per encoder turn, absolute resolution) for the raw data of the encoder is invalid. E.g. this value is used for axis reference sequence (calibration) with the reference mode Software Sync."},
    17447: { "type": "Parameter", "desc": "Parameter Dead Time Compensation Mode (Encoder) is Invalid"},
    17448: { "type": "Parameter", "desc": "Parameter “Control Bits of Dead Time Compensation” (Encoder) is Invalid"},
    17449: { "type": "Parameter", "desc": "Parameter “Time Related Shift of Dead Time Compensation Mode” (Encoder) is Invalid"},
    17456: { "type": "Function", "desc": "Hardware latch activation (encoder)"},
    17457: { "type": "Function", "desc": "External hardware latch activation (encoder)"},
    17458: { "type": "Function", "desc": "External hardware latch activation (encoder)"},
    17459: { "type": "Function", "desc": "External hardware latch activation (encoder)"},
    17460: { "type": "Monitoring", "desc": "Encoder function not supported"},
    17461: { "type": "Monitoring", "desc": "Encoder function is already active"},
    17472: { "type": "Initialization", "desc": "Encoder initialization: Encoder has not been initialized"},
    17473: { "type": "Address", "desc": "Axis address: The encoder does not have an axis, or the axis address has not been initialized"},
    17474: { "type": "Address", "desc": "I/O input structure address: The drive does not have a valid I/O input address in the process image"},
    17475: { "type": "Address", "desc": "I/O output structure address The encoder does not have a valid I/O output address in the process image."},
    17488: { "type": "Monitoring", "desc": "Encoder counter underflow monitoring: The encoder's incremental counter has underflowed"},
    17489: { "type": "Monitoring", "desc": "Encoder counter overflow monitoring: The encoder's incremental counter has overflowed"},
    17504: { "type": "Monitoring", "desc": "Minimum Software Position Limit (Axis Start)"},
    17505: { "type": "Monitoring", "desc": "Maximum Software Position Limit (Axis Start)"},
    17506: { "type": "Monitoring", "desc": "Minimum Software Position Limit (Positioning Process)"},
    17507: { "type": "Monitoring", "desc": "Maximum Software Position Limit (Positioning Process)"},
    17508: { "type": "Monitoring", "desc": "Encoder hardware error"},
    17509: { "type": "Monitoring", "desc": "Position initialization error at system start"},
    17510: { "type": "Monitoring", "desc": "Invalid IO data for more than n subsequent NC cycles (encoder)"},
    17511: { "type": "Monitoring", "desc": "Invalid Actual Position (Encoder)"},
    17512: { "type": "Monitoring", "desc": "Invalid IO Input Data (Error Type 1)"},
    17513: { "type": "Monitoring", "desc": "Invalid IO Input Data (Error Type 2)"},
    17520: { "type": "Monitoring", "desc": "SSI transformation fault or not finished"},
    17570: { "type": "Monitoring", "desc": "ENCERR_ADDR_CONTROLLER"},
    17571: { "type": "Monitoring", "desc": "ENCERR_INVALID_CONTROLLERTYPE"},
    17664: { "type": "Parameter", "desc": "Controller ID not allowed"},
    17665: { "type": "Parameter", "desc": "Controller type not allowed"},
    17666: { "type": "Parameter", "desc": "Controller operating mode not allowed"},
    17667: { "type": "Parameter", "desc": "Weighting of the velocity pre-control not allowed"},
    17668: { "type": "Parameter", "desc": "Following error monitoring (position) not allowed"},
    17669: { "type": "Parameter", "desc": "Following error (velocity) not allowed"},
    17670: { "type": "Parameter", "desc": "Following error window (position) not allowed"},
    17671: { "type": "Parameter", "desc": "Following error filter time (position) not allowed"},
    17672: { "type": "Parameter", "desc": "Following error window (velocity) not allowed"},
    17673: { "type": "Parameter", "desc": "Following error filter time (velocity) not allowed"},
    17674: { "type": "Parameter", "desc": "Controller Output Limitation Improper"},
    17680: { "type": "Parameter", "desc": "Proportional gain Kv or Kp (controller) not allowed"},
    17682: { "type": "Parameter", "desc": "Derivative action time Tv (controller) not allowed"},
    17683: { "type": "Parameter", "desc": "Damping time Td (controller) not allowed"},
    17684: { "type": "Function", "desc": "Activation of the automatic offset compensation not allowed"},
    17685: { "type": "Parameter", "desc": "Additional proportional gain Kv or Kp (controller) not allowed"},
    17686: { "type": "Parameter", "desc": "Reference velocity for additional proportional gain Kv or Kp (controller) not allowed"},
    17687: { "type": "Parameter", "desc": "Proportional gain Pa (proportion) not allowed"},
    17688: { "type": "Parameter", "desc": "Proportional gain Kv (velocity controller) not allowed"},
    17689: { "type": "Parameter", "desc": "Reset time Tn (velocity controller) not allowed"},
    17690: { "type": "Parameter", "desc": "Reserved"},
    17691: { "type": "Parameter", "desc": "Reserved"},
    17692: { "type": "Parameter", "desc": "Velocity Filter Time Improper"},
    17693: { "type": "Parameter", "desc": "Dead zone not allowed"},
    17695: { "type": "Parameter", "desc": "Proportionality Factor Kcp Improper"},
    17696: { "type": "Parameter", "desc": "Rate time Tv (velocity controller) not allowed"},
    17697: { "type": "Parameter", "desc": "Damping time Td (velocity controller) not allowed"},
    17698: { "type": "Parameter", "desc": "Limitation of the I Part Improper"},
    17699: { "type": "Parameter", "desc": "Limitation of the D Part Improper"},
    17700: { "type": "Parameter", "desc": "Parameter 'Switching Off the I Part During Motion' is Improper"},
    17701: { "type": "Parameter", "desc": "Parameter 'Filter Time for P-T2 Filter' Improper"},
    17702: { "type": "Parameter", "desc": "Velocity Observer: 'Parameterized Mode' is Improper"},
    17703: { "type": "Parameter", "desc": "Velocity Observer: 'Motor Torque Constant Kt or Kf' is Improper"},
    17704: { "type": "Parameter", "desc": "Velocity Observer: 'Motor Moment of Inertia JM' is Improper"},
    17705: { "type": "Parameter", "desc": "Velocity Observer: 'Band Width f0' is Improper"},
    17706: { "type": "Parameter", "desc": "Velocity Observer: 'Correction Factor kc' is Improper"},
    17707: { "type": "Parameter", "desc": "Velocity Observer: 'Time Constant T for First Order Filter' is Improper"},
    17708: { "type": "Parameter", "desc": "Velocity Observer: 'Amplitude Damping d for Second Order Filter' is Improper"},
    17709: { "type": "Parameter", "desc": "Velocity Observer: 'Frequency fHP or Frequency fTP for Filters of Second Order' is Improper"},
    17728: { "type": "Initialization", "desc": "Controller initialization: Controller has not been initialized"},
    17729: { "type": "Address", "desc": "Axis address: Controller does not know its axis, or the axis address has not been initialized"},
    17730: { "type": "Address", "desc": "Drive address: Controller does not know its drive, or the drive address has not been initialized"},
    17744: { "type": "Monitoring", "desc": "Following error monitoring (position)"},
    17745: { "type": "Monitoring", "desc": "Following error monitoring (velocity)"},
    17824: { "type": "Monitoring", "desc": "CONTROLERR_RANGE_AREA_ASIDE"},
    17825: { "type": "Monitoring", "desc": "CONTROLERR_RANGE_AREA_BSIDE"},
    17826: { "type": "Monitoring", "desc": "CONTROLERR_RANGE_QNENN"},
    17827: { "type": "Monitoring", "desc": "CONTROLERR_RANGE_PNENN"},
    17828: { "type": "Monitoring", "desc": "CONTROLERR_RANGE_AXISIDPRESP0"},
    17920: { "type": "Parameter", "desc": "Drive ID not allowed"},
    17921: { "type": "Parameter", "desc": "Drive type not allowed"},
    17922: { "type": "Parameter", "desc": "Drive operation mode not allowed"},
    17923: { "type": "Parameter", "desc": "Motor polarity inverted?"},
    17924: { "type": "Parameter", "desc": "Drift compensation/speed offset (DAC offset)"},
    17925: { "type": "Parameter", "desc": "Reference velocity (velocity pre-control)"},
    17926: { "type": "Parameter", "desc": "Reference output in percent: The value for the reference output in percent is not allowed."},
    17927: { "type": "Parameter", "desc": "Quadrant compensation factor: The value for the quadrant compensation factor is not allowed"},
    17928: { "type": "Parameter", "desc": "Velocity reference point in percent: The value for the velocity reference point in percent is not allowed"},
    17929: { "type": "Parameter", "desc": "Output reference point in percent: The value for the output reference point in percent is not allowed"},
    17930: { "type": "Parameter", "desc": "Minimum or maximum output limits (output limitation): The value for the minimum and/or maximum output limit is not allowed"},
    17931: { "type": "Parameter", "desc": "Parameter 'Maximum value for output' is not allowed"},
    17932: { "type": "Parameter", "desc": "Parameter 'Internal Drive Control Word' is not allowed"},
    17933: { "type": "Parameter", "desc": "Parameter 'Internal timer for RESET behavior Drive' is not allowed"},
    17934: { "type": "Parameter", "desc": "Parameter 'Master Motion Controller ID' is not allowed"},
    17935: { "type": "Parameter", "desc": "Drive torque output scaling not allowed"},
    17936: { "type": "Parameter", "desc": "Drive velocity output scaling not allowed"},
    17937: { "type": "Parameter", "desc": "Profi Drive DSC proportional gain Kpc (controller) not allowed"},
    17938: { "type": "Parameter", "desc": "Table ID is not allowed"},
    17939: { "type": "Parameter", "desc": "Table interpolation type is not allowed"},
    17940: { "type": "Parameter", "desc": "Output offset in percent is not allowed"},
    17941: { "type": "Parameter", "desc": "Profi Drive DSC scaling for calculation of 'Xerr' (controller) not allowed"},
    17942: { "type": "Parameter", "desc": "Drive acceleration output scaling not allowed"},
    17943: { "type": "Parameter", "desc": "Drive position output scaling not allowed"},
    17944: { "type": "Parameter", "desc": "Parameter 'Dead time compensation mode' (Motion Controller) is invalid"},
    17945: { "type": "Parameter", "desc": "Parameter 'Control bits of the dead time compensation' (Motion Controller) is invalid"},
    17946: { "type": "Parameter", "desc": "Parameter 'time shift of dead time compensation mode' (Motion Controller) is invalid"},
    17947: { "type": "Parameter", "desc": "Parameter 'Output delay velocity interface Motion Controller' is invalid"},
    17948: { "type": "Parameter", "desc": "Drive filter type not allowed for command variable filter for the output position"},
    17949: { "type": "Parameter", "desc": "Drive filter time not allowed for command variable filter for the output position"},
    17950: { "type": "Parameter", "desc": "Drive filter order not allowed for command variable filter for the output position"},
    17952: { "type": "Parameter", "desc": "Bit mask for stepper motor cycle not allowed"},
    17953: { "type": "Parameter", "desc": "Bit mask for stepper motor holding current not allowed"},
    17954: { "type": "Parameter", "desc": "Scaling factor for actual torque (actual current) not allowed"},
    17955: { "type": "Parameter", "desc": "Filter time for actual torque is not allowed"},
    17956: { "type": "Parameter", "desc": "Filter time for the temporal derivation of the actual torque is not allowed"},
    17957: { "type": "Parameter", "desc": "Parameter 'Drive operation mode' is invalid"},
    17958: { "type": "Monitoring", "desc": "Motion Controller function is not supported"},
    17959: { "type": "Function", "desc": "DRIVE OPERATION MODE BUSY"},
    17960: { "type": "Monitoring", "desc": "Drive operation mode changeover is not configured or the desired drive operation mode cannot be found"},
    17961: { "type": "Monitoring", "desc": "Feedback drive operation mode changeover"},
    17968: { "type": "Monitoring", "desc": "Overtemperature"},
    17969: { "type": "Monitoring", "desc": "Undervoltage"},
    17970: { "type": "Monitoring", "desc": "Open circuit in phase A"},
    17971: { "type": "Monitoring", "desc": "Open circuit in phase B"},
    17972: { "type": "Monitoring", "desc": "Overcurrent in phase A"},
    17973: { "type": "Monitoring", "desc": "Overcurrent in phase B"},
    17974: { "type": "Monitoring", "desc": "Torque overload (stall)"},
    17984: { "type": "Initialization", "desc": "Drive initialization"},
    17985: { "type": "Address", "desc": "Axis address: Drive does not know its axis, or the axis address has not been initialized"},
    17986: { "type": "Address", "desc": "Address I/O input structure: Drive has no valid I/O input address in the process image"},
    17987: { "type": "Address", "desc": "Address I/O output structure: Drive has no valid I/O output address in the process image"},
    18000: { "type": "Monitoring", "desc": "Drive hardware not ready to operate"},
    18001: { "type": "Monitoring", "desc": "Error in the cyclic communication of the drive (Life Counter) "},
    18002: { "type": "Monitoring", "desc": "Changing the table ID when active controller enable is not allowed"},
    18005: { "type": "Monitoring", "desc": "Invalid I/O data for more than 'n' continuous NC cycles"},
    19200: { "type": "Parameter", "desc": "Axis was stopped"},
    19201: { "type": "Parameter", "desc": "Axis cannot be started"},
    19202: { "type": "Parameter", "desc": "Control mode not permitted"},
    19203: { "type": "Parameter", "desc": "Axis is not moving"},
    19204: { "type": "Parameter", "desc": "“Invalid mode”"},
    19205: { "type": "Parameter", "desc": "Command not permitted"},
    19206: { "type": "Parameter", "desc": "Parameter incorrect"},
    19207: { "type": "Parameter", "desc": "Timeout axis function block"},
    19208: { "type": "Parameter", "desc": "Axis is in protected mode"},
    19209: { "type": "Parameter", "desc": "Axis is not ready"},
    19210: { "type": "Parameter", "desc": "Error during referencing"},
    19211: { "type": "Parameter", "desc": "Incorrect definition of the trigger input"},
    19212: { "type": "Function", "desc": "Position latch was disabled"},
    19213: { "type": "Function", "desc": "NC status feedback timeout"},
    19214: { "type": "Function", "desc": "Additional product not installed"},
    19215: { "type": "Function", "desc": "No NC Cycle Counter Update"},
    19216: { "type": "Function", "desc": "M-function query missing"},
    19217: { "type": "Parameter", "desc": "Zero shift index is outside the range"},
    19218: { "type": "Parameter", "desc": "R-parameter index or size is invalid"},
    19219: { "type": "Parameter", "desc": "Index for tool description is invalid"},
    19220: { "type": "Function", "desc": "Version of the cyclic channel interface does not match the requested function or the function block"},
    19221: { "type": "Function", "desc": "Channel is not ready for the requested function"},
    19222: { "type": "Function", "desc": "Requested function is not activated"},
    19223: { "type": "Function", "desc": "Axis is already in another group"},
    19224: { "type": "Function", "desc": "Block search could not be executed successfully"},
    19225: { "type": "Parameter", "desc": "Invalid block search parameter"},
    19232: { "type": "Function", "desc": "Cannot add all axes"},
    19248: { "type": "Parameter", "desc": "Pointer is invalid"},
    19249: { "type": "Parameter", "desc": "Memory size invalid"},
    19250: { "type": "Parameter", "desc": "Cam table ID is invalid"},
    19251: { "type": "Parameter", "desc": "Point ID is invalid"},
    19252: { "type": "Parameter", "desc": "Number of points is invalid"},
    19253: { "type": "Parameter", "desc": "MC table type is invalid"},
    19254: { "type": "Parameter", "desc": "Number of rows invalid"},
    19255: { "type": "Parameter", "desc": "Number of columns invalid"},
    19256: { "type": "Parameter", "desc": "Step size invalid"},
    19264: { "type": "Monitoring", "desc": "Terminal type not supported"},
    19265: { "type": "Monitoring", "desc": "Register read/write error"},
    19266: { "type": "Monitoring", "desc": "Axis is enabled"},
    19267: { "type": "Parameter", "desc": "Incorrect size of the compensation table"},
    19268: { "type": "Parameter", "desc": "The minimum/maximum position in the compensation table does not match the position in the table description (ST_CompensationDesc)"},
    19269: { "type": "Parameter", "desc": "Not implemented"},
    19270: { "type": "Parameter", "desc": "Window not in the specified modulo range"},
    19271: { "type": "Monitoring", "desc": "Buffer overflow"},
    19296: { "type": "Monitoring", "desc": "Motion command did not become active"},
    19297: { "type": "Monitoring", "desc": "Motion command could not be monitored by the PLC"},
    19298: { "type": "Monitoring", "desc": "Buffered command was terminated with an error"},
    19299: { "type": "Monitoring", "desc": "Buffered command was completed without feedback"},
    19300: { "type": "Monitoring", "desc": " 'BufferMode' is not supported by the command"},
    19301: { "type": "Monitoring", "desc": "Command number is zero"},
    19302: { "type": "Monitoring", "desc": "Function block was not called cyclically"},
    19313: { "type": "Parameter", "desc": "Invalid NCI entry type"},
    19314: { "type": "Function", "desc": "NCI feed table full"},
    19315: { "type": "Function", "desc": "internal error"},
    19316: { "type": "Parameter", "desc": "ST_NciTangentialFollowingDesc: Tangential axis is not an auxiliary axis"},
    19317: { "type": "Parameter", "desc": "ST_NciTangentialFollowingDesc: nPathAxis1 or nPathAxis2 is not a path axis"},
    19318: { "type": "Parameter", "desc": "ST_NciTangentialFollwoingDesc: nPathAxis1 and nPathAxis2 are the same"},
    19319: { "type": "Parameter", "desc": "ST_NciGeoCirclePlane: Circle incorrectly parameterized"},
    19320: { "type": "Function", "desc": "Internal error during calculation of tangential following"},
    19321: { "type": "Monitoring", "desc": "Tangential following: Monitoring of the deviation angle was activated during activation of tangential following (E_TfErrorOnCritical1), and an excessively large deviation angle was detected in the current segment"},
    19322: { "type": "Function", "desc": "not implemented"},
    19323: { "type": "Parameter", "desc": "Tangential following: the radius of the current arc is too small"},
    19324: { "type": "Parameter", "desc": "FB_NciFeedTablePreparation: pEntry is NULL"},
    19325: { "type": "Parameter", "desc": "FB_NciFeedTablePreparation: the specified nEntryType does not match the structure type"},
    19326: { "type": "Parameter", "desc": "ST_NciMFuncFast and ST_NciMFuncHsk: the requested M-function is not between 0 and 159"},
    19327: { "type": "Parameter", "desc": "ST_NciDynOvr: the requested value for the dynamic override is not between 0.01 and 1"},
    19328: { "type": "Parameter", "desc": "ST_NciVertexSmoothing: invalid parameter"},
    19329: { "type": "Parameter", "desc": "FB_NciFeedTablePrepartion: The requested velocity is not in the valid range"},
    19330: { "type": "Parameter", "desc": "ST_Nci*: invalid parameter"},
    19344: { "type": "Parameter", "desc": "Determined drive typeis not supported"},
    19345: { "type": "Parameter", "desc": "Directionis impermissible"},
    19346: { "type": "Internal", "desc": "SwitchModeis impermissible"},
    19347: { "type": "Internal", "desc": "Modefor the parameter handling is impermissible"},
    19348: { "type": "Internal", "desc": "Parameterization of the torque limits is inconsistent"},
    19349: { "type": "Internal", "desc": "Parameterization of the position lag limit is impermissible (<=0)"},
    19350: { "type": "Internal", "desc": "Parameterization of the distance limit is impermissible (<0)"},
    19351: { "type": "Internal", "desc": "An attempt was made to back up parameters again, although they have already been backed up"},
    19352: { "type": "Internal", "desc": "An attempt was made to restore parameters, although none have been backed up"},
    19359: { "type": "Internal", "desc": "The abortion of a homing has failed"},
    19361: { "type": "Function", "desc": "KinGroup timeout:timeout during call of a kinematic block"},
    19376: { "type": "Function", "desc": "The current axis position or the axis position resulting from the new position offset exceeds the valid range of values"},
    19377: { "type": "Function", "desc": "The new position offset exceeds the valid range of values [AX5000: 2^31]"},
    19378: { "type": "Function", "desc": "The current axis position or the axis position resulting from the new position offset falls below the valid range of values"},
    19379: { "type": "Function", "desc": "The new position offset falls below the valid range of values [AX5000: -2^31]"},
    19380: { "type": "Function", "desc": "The activated feedback and/or storage location (AX5000: P-0-0275) differ from the parameterization on the function block"},
    19381: { "type": "Function", "desc": "Reinitialization of the actual NC position has failed"},
    19382: { "type": "Function", "desc": "The command to set or delete a position offset was rejected without feedback data"},
    19383: { "type": "Function", "desc": "The command to set or delete a position offset was rejected with feedback data"},
    19384: { "type": "Function", "desc": "A firmware version >= 19 is required for the servo terminal"},
    19385: { "type": "Function", "desc": "The modulo settings on the drive controller and NC are different"},
    19394: { "type": "Internal", "desc": "The new position offset exceeds the valid value range"},
    19395: { "type": "Internal", "desc": "I/O data are invalid or the terminal is in an error state"},
}

def get_error_msg(code: int) -> str:
    error = ERROR_CODES.get(code)
    if error is None:
        return "Internal Error"
    else:
        return f"{error['type']} Error[{code}]: {error['desc']}"


